name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - prod

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENV: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npx playwright install --with-deps

      - run: npm run test:${{ github.event.inputs.environment }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report